rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    #url(r'index/', views.index, name='index'),
    url(r'about/$', views.about, name='about'),
    url(r'category/(?P<category_name_slug>[\w\-]+)/$',
        views.show_category, name='show_category'),
    url(r'add_category/$', views.add_category, name='add_category'),
    url(r'category/(?P<category_name_slug>[\w\-]+)/add_page/$',
        views.add_page, name='add_page'),
    url(r'register/$', views.register, name='register'),
    url(r'user_login/&', views.user_login, name='user_login'),
]

tango_with_django_project/urls.py
# basic
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

# media
from django.conf import settings
from django.conf.urls.static import static

# project
from rango import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rango/', include('rango.urls')),
    # above maps any urls starting with rango/ to be handled by the rango application.
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(default='', unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField(default='')
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    # Necessary, links UserProfile to User model
    user = models.OneToOneField(User)

    # Additional attributes
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override unicode method to print useful information
    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile

max_length = 128
max_url_length = 200

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=max_length,
        help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        # Make association between Category and ModelForm
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=max_length,
        help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=max_url_length,
        help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Make association between Page and ModelForm
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # Check if url exists and if it doesnt begin with http://
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

        return cleaned_data

# User registration
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse
from datetime import datetime

# import models
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm

# Define different views to send a reponse to
def index(request):
    request.session.set_test_cookie()

    # Retrieve top 5 Categories and Pages, '-' means descending order.
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by("-views")[:5]
    context_dict = {'categories': category_list, 'pages': page_list}

    # Create cookies
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    # Return response to user
    return render(request, 'rango/index.html', context_dict)

def visitor_cookie_handler(request):
    # Get number of visitors to the site
    # If cookie exists, use 'visits' value otherwise default to 1
    visits = int(get_server_side_cookie(request, 'visits', 1))

    # Get time from last visit
    last_visit_cookie = get_server_side_cookie(
        request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                        '%Y-%m-%d %H:%M:%S')

    # If its been more than a day
    if(datetime.now() - last_visit_time).seconds > 0:
        visits = visits + 1
        # Update the last visit cookie to now
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    # Update the visits cookie
    request.session['visits'] = visits

# Helper function to check if requested cookie is in session data,
# If not, returns default value
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def about(request):
    if request.session.test_cookie_worked():
        print("Test cookie worked.")
        request.session.delete_test_cookie()

    context_dict = {'boldmessage': "Crunchy, creamy, cookie, candy, cupcake!",
        'visits': request.session['visits']}
    return render(request, 'rango/about.html', context=context_dict)

def show_category(request, category_name_slug):
    # Contect dictionary to be passed to template rendering engine
    context_dict = {}

    # Try to find category with given slug name,
    # Then add it's associated pages to the contect dictionary
    # Otherwise, add None to dictionary
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category

    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None

    return render(request, 'rango/category.html', context_dict)

def add_category(request):
    form = CategoryForm()

    # A http post?
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        # Check validity
        if form.is_valid():
            form.save(commit=True) # Save to database
            return index(request)
        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})

def add_page(request, category_name_slug):
    category = Category.objects.get(slug=category_name_slug)
    form = PageForm()

    # A http post?
    if request.method == 'POST':
        print("Post recieved.")
        form = PageForm(request.POST)

        # Check validity
        if form.is_valid():
            print("Valid form.")
            page = form.save(commit=False) # Save to database
            page.category = category
            page.views = 0
            page.save()
            return show_category(request, category_name_slug)
        else:
            print(form.errors)

    pages = Page.objects.filter(category=category)
    context_dict = {'form':form, 'category':category, 'pages':pages}
    return render(request, 'rango/add_page.html', context_dict)

# User registration
def register(request):
    registered = False

    # If request is a http POST, process form
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # Check if forms are valid
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            # Hash user password, save.
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            # Profile picture?
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Save
            profile.save()
            registered = True
        else:
            # Invalid forms, print problems to terminal
            print(user_form.errors, profile_form.errors)
    else:
        # Not a http POST, so render registration form
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render
    context_dict = {'user_form': user_form, 'profile_form': profile_form,
                    'registered': registered}
    return render(request, 'rango/register.html', context_dict)

# Log in
def user_login(request):
    # A http post?
    if request.method == 'POST':
        # Get input from user
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Use django machinery to validate
        user = authenticate(username=username, password=password)

        # If correct, user object is created
        if user:
            # Check if user has been disabled
            if user.is_active:
                # If user is valid and active, log in
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                # An inactive account was used
                return HttpResponse("Your account is disabled.")
        else:
            # Bad login details provided
            print("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied.")

    # If not a http post, display log in form.
    else:
        return render(request, 'rango/user_login.html', {})

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %} <!-- New line -->

{% block title_block %}
  About
{% endblock %}

{% block body_block %}
  <div>
    Rango says here is the about page.<br />
    <strong>{{ boldmessage }}</strong><br />
    <p>Number of visits: {{ visits }}</p>
    This tutorial has been put together by Charles Varley.
  </div>
  <div>
    <img src="{% static 'images/rango2.jpg' %}" alt="Picture of Rango" />
    <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat" />
  </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% block title_block %}
  Add a Category
{% endblock %}

{% block body_block %}
  <h1>Add a Category</h1>
  <div>
    <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}
      {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
      {% endfor %}
      <input type="submit" name="submit" value="Create Category" />
    </form>
  </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}

{% block title_block %}
  Add a Page
{% endblock %}

{% block body_block %}
  <h1>{{ category.name }}</h1>
  <h2>Current Pages:</h2>
  <ul>
    {% for page in pages %}
      <li>{{ page.title }}</li>
    {% endfor %}
  </ul>

  <h2>Add a Page</h2>
  <div>
    <form id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}
      {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}<br />
      {% endfor %}
      <input type="submit" name="submit" value="Create Page" />
    </form>
  </div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <head lang="en">
    <meta charset="UTF-8" />
    <title>
      Rango -
      {% block title_block %}
        How to Tango with Django!
      {% endblock %}
    </title>
  </head>
  <body>
    <div>
      {% block body_block %}
      {% endblock %}
    </div>
    <hr />
    <div>
      <ul>
        <li><a href="{% url 'rango:index' %}">Index</a></li>
        <li><a href="{% url 'rango:about' %}">About</a></li>
        {% if user.is_authenticated %}
          <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
          <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
          <li><a href="{% url 'rango:user_logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
          <li><a href="{% url 'rango:user_login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  {{ category.name }}
{% endblock %}

{% block body_block %}
  {% if category %}
    <h1>{{ category.name }}</h1>

    {% if pages %}
      <ul>
        {% for page in pages %}
          <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}
      </ul>
    {% else %}
      <strong>No pages currently in directory.</strong>
    {% endif %}
    {% if user.is_authenticated %}
      <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a><br />
    {% endif %}
  {% else %}
    The specified category does not exist!
  {% endif %}
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Welcome
{% endblock %}

{% block body_block %}
  <h1>Rango says...</h1>
  {% if user.is_authenticated %}
    howdy {{ user.username }}!
  {% else %}
    hey there partner!
  {% endif %}

  <div>
    <p>Number of visits: {{ visits }}</p>
    {% if categories %}
      <!-- List top 5 categories -->
      <h2>Most Liked Categories:</h2>
      <ul>
        {% for category in categories %}
          <li><a href="{% url 'rango:show_category' category.slug %}">
            {{ category.name }}</a></li>
        {% endfor %}
      </ul>

      <!-- List top 5 pages -->
      <h2>Most Viewed Pages:</h2>
        <ol>
          {% for page in pages %}
            <li><a href="{{ page.url }}">
            {{ page.title }}</a> : {{ page.views }} views</li>
          {% endfor %}
        </ol>
    {% else %}
      <strong>There are no categories present.</strong>
    {% endif %}
  </div>
  <div>
    <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
  </div>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Register
{% endblock %}

{% block body_block %}
  <h1>Register for Rango</h1>
  {% if registered %}
    Rango says: <strong>Thank you for registering!</strong>
    <a href="{% url 'index' %}">Return to homepage.</a><br />
  {% else %}
    Rango says: <strong>Register here!</strong><br />
    <form id="user_form" method="post" action="{% url 'rango:register' %}"
      enctype="multipart/form-data">
      {% csrf_token %}

      <!-- Display each form -->
      {{ user_form.as_p }}
      {{ profile_form.as_p }}

      <!-- Provide button to submit form -->
      <input type="submit" name="submit" value="register" />
    </form>
  {% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  {{ category.name }}
{% endblock %}

{% block body_block %}
  Since you are logged in, you can see this text!
{% endblock %}

templates/rango/user_login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Login
{% endblock %}

{% block body_block %}
  <h1>Login to Rango</h1>
  <form id="login_form" method="post" action="{% url 'rango:user_login' %}">
    {% csrf_token %}

    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="text" name="password" value="" size="50" />
    <br />

    <input type="submit" value="submit" />
  </form>
{% endblock %}